const {
    RUNTIME_NODE_MODEL_CAPABILITY_ID,
    RUNTIME_NODE_SNAPSHOT_CAPABILITY_ID,
    RUNTIME_NODE_TYPE_REGISTRATION_CAPABILITY_ID
} = require('../runtime-nodes/constants');
const {SCRATCH_SPRITE_ADAPTER_CAPABILITY_ID} = require('../scratch-sprite-adapter/constants');

const SCENE_DATA_SCHEMA_VERSION = 1;
const SCENE_VARIABLE_SCHEMA_VERSION = 1;
const SCENE_SYSTEM_MODULE_ID = 'ngvge.scene-system';
const SCENE_DATA_MODEL_CAPABILITY_ID = 'ngvge.scene-data-model';
const SCENE_CONTROLLER_CAPABILITY_ID = 'ngvge.scene-controller';
const SCENE_SNAPSHOT_CAPABILITY_ID = 'ngvge.scene-snapshot-serializer';
const SCENE_RUNTIME_CAPABILITY_ID = 'ngvge.scene-runtime';
const SCENE_MANAGER_CAPABILITY_ID = 'ngvge.scene-manager';
const SCENE_PERSISTENCE_REVIEW_CAPABILITY_ID = 'ngvge.scene-persistence-review';
const SCENE_SNAPSHOT_FORMAT = 'ngvge-portable-scene';
const SCENE_SNAPSHOT_ENCODING = 'json-base64-files';
const SCENE_SNAPSHOT_SCHEMA_VERSION = 2;
const LEGACY_SCENE_SNAPSHOT_FORMAT = 'ngvge-sb3-scene';
const LEGACY_SCENE_SNAPSHOT_ENCODING = 'base64';
const LEGACY_SCENE_SNAPSHOT_SCHEMA_VERSION = 1;
const FIRST_PARTY_MODULE_PROJECT_SECTION_ID = 'ngvge-first-party-modules';

const SCENE_ID_PREFIX = 'scene';
const SCENE_VARIABLE_ID_PREFIX = 'scene-variable';

const VARIABLE_SCOPES = Object.freeze({
    GLOBAL: 'global',
    SCENE: 'scene',
    TARGET: 'target'
});

const VARIABLE_TYPES = Object.freeze({
    LIST: 'list',
    SCALAR: 'scalar'
});

module.exports = {
    FIRST_PARTY_MODULE_PROJECT_SECTION_ID,
    SCENE_CONTROLLER_CAPABILITY_ID,
    SCENE_DATA_MODEL_CAPABILITY_ID,
    SCENE_DATA_SCHEMA_VERSION,
    SCENE_ID_PREFIX,
    RUNTIME_NODE_MODEL_CAPABILITY_ID,
    RUNTIME_NODE_SNAPSHOT_CAPABILITY_ID,
    RUNTIME_NODE_TYPE_REGISTRATION_CAPABILITY_ID,
    SCRATCH_SPRITE_ADAPTER_CAPABILITY_ID,
    SCENE_MANAGER_CAPABILITY_ID,
    SCENE_PERSISTENCE_REVIEW_CAPABILITY_ID,
    SCENE_RUNTIME_CAPABILITY_ID,
    SCENE_SNAPSHOT_CAPABILITY_ID,
    LEGACY_SCENE_SNAPSHOT_ENCODING,
    LEGACY_SCENE_SNAPSHOT_FORMAT,
    LEGACY_SCENE_SNAPSHOT_SCHEMA_VERSION,
    SCENE_SNAPSHOT_ENCODING,
    SCENE_SNAPSHOT_FORMAT,
    SCENE_SNAPSHOT_SCHEMA_VERSION,
    SCENE_SYSTEM_MODULE_ID,
    SCENE_VARIABLE_ID_PREFIX,
    SCENE_VARIABLE_SCHEMA_VERSION,
    VARIABLE_SCOPES,
    VARIABLE_TYPES
};
